### ISSUE TITLE
Django 1.7+ and App registry.

### ISSUE THREAD

**Issue by bitmonkey** [danfairs/django-dfk#9]
DFK's point named is currently using methods db.models.loading which is a legacy module currently pointing to the app registry methods for the same calls, this bridging module will disappear in Django 1.9.

If people don't have strong objections I'd like to replace the calls to get_models in point_named in Django 1.7+ to instead directly index into the app_registry. 

I'm aware we could replace the call with calls to `get_models()` on the registry itself `django.apps.registry.apps.get_models()`, but that causes an issue with our use of DFK which does things before the registry is marked as ready which means that calls to query the registry will make Django throw it's toys out of the pram....direct registry access avoids this marshalling.

**Comment by danfairs** [comment]
Sounds fine.

The README says that dfk is compatible with Django 1.3 onwards. Is that already out-of-date?

**Comment by bitmonkey** [comment]
Out of date?? 

It's currently tested and with all the tests  passing against 1.3 - 1.7, and I updated README, the tox config and `install_requires` in`setup.py` to reflect the tested / supported versions when I released v0.0.10. 

I've not had chance to test against 1.8+, expect this will happen in few months time as we'll be moving to 1.8 ASAP as that's the next LTS release....for now I'm having enough fun porting your old modelgen code to work under the shackles of 1.7's app refactor ;)

**Comment by bitmonkey** [comment]
Closing this, will reopen this can of works when we support 1.9, for now 1.8 is the focus.
